<?php

namespace Database\Seeders;

use App\Models\LifestyleCategory;
use Illuminate\Database\Seeder;

class LifestyleCategorySeeder extends Seeder
{
    public function run(): void
    {
        $categories = [
            'Beauty & Personal Care Services' => [
                'Hair Salon',
                'Barber Shop',
                'Nail Care',
                'Eyelash & Brow Services',
                'Facial & Skin Care',
                'Makeup Services',
                'Spa & Massage',
                'Waxing Services',
                'Body Treatments',
                'Grooming Services',
                'Aesthetic Services',
                'Skin Clinics',
            ],

            'Health & Medical Services' => [
                'Medical Clinic',
                'General Consultation',
                'Specialists Clinic',
                'Diagnostic Centers',
                'Laboratory Services',
                'Vaccination Services',
                'Home Healthcare',
                'Ambulance Services',
                'Dental Clinic',
                'Dental Cleaning',
                'Orthodontics',
                'Teeth Whitening',
                'Dentures',
                'Oral Surgery',
                'OB-GYN Services',
                'Prenatal Care',
                'Maternity Services',
                'Pediatric Clinic',
                'Family Planning',
                'Physical Therapy',
                'Occupational Therapy',
                'Speech Therapy',
                'Mental Health Counseling',
                'Psychological Services',
            ],

            'Wellness, Fitness & Coaching' => [
                'Gym & Fitness Center',
                'Personal Training',
                'Yoga Classes',
                'Dance Classes',
                'Martial Arts Training',
                'Nutrition Coaching',
                'Life Coaching',
                'Business Coaching',
                'Career Coaching',
                'Financial Coaching',
                'Wellness Programs',
            ],

            'Education & Training Services' => [
                'Tutoring Center',
                'Review Center',
                'Learning Center',
                'Day Care Services',
                'Preschool Programs',
                'SPED Services',
                'Homeschool Support',
                'Computer Lessons',
                'TESDA Training',
                'Baking Classes',
                'Cooking Classes',
                'Sewing Classes',
                'Driving School',
                'Language Classes',
                'Music Lessons',
                'Arts Workshops',
                'Gardening Tutorial',
                'Farming Seminar',
                'Plant Care Coaching',
                'Hydroponics Training',
                'Livestock Training',
                'Digital Skills Training',
            ],

            'Pet Care & Veterinary Services' => [
                'Veterinary Clinic',
                'Pet Consultation',
                'Vaccination',
                'Surgery',
                'Deworming',
                'Pet Laboratory',
                'Pet Grooming',
                'Pet Hotel',
                'Pet Boarding',
                'Pet Day Care',
                'Pet Training',
                'Pet Sitting',
                'Kapon Services',
                'Breeding Services',
                'Pet Adoption Assistance',
            ],

            'Construction, Engineering & Home Services' => [
                'House Construction',
                'Commercial Construction',
                'Renovation Services',
                'Fit-out Services',
                'Roofing Services',
                'Painting Services',
                'Masonry',
                'Carpentry',
                'Welding',
                'Plumbing',
                'Electrical Services',
                'Civil Engineering',
                'Architectural Design',
                'Structural Design',
                'Quantity Surveying',
                'Project Management',
                'Interior Design',
                'Modular Cabinets',
                'Furniture Installation',
                'CCTV Installation',
                'Solar Installation',
                'Smart Home Setup',
                'General Cleaning',
                'Deep Cleaning',
                'Pest Control',
                'Landscaping',
                'Gardening Services',
                'Pool Maintenance',
            ],

            'Repair & Maintenance Services' => [
                'Aircon Repair',
                'Refrigerator Repair',
                'Washing Machine Repair',
                'Appliance Troubleshooting',
                'Computer Repair',
                'Laptop Repair',
                'Cellphone Repair',
                'Printer Repair',
                'CCTV Repair',
                'Auto Repair',
                'Motorcycle Repair',
                'Vulcanizing',
                'Car Detailing',
                'Battery Services',
                'Furniture Repair',
                'Roofing Repair',
                'Plumbing Repair',
                'Electrical Repair',
            ],

            'Printing, Digital & Creative Services' => [
                'Photocopying',
                'Tarpaulin Printing',
                'Sticker Printing',
                'T-shirt Printing',
                'Invitation Printing',
                'ID Printing',
                'Souvenir Printing',
                'Graphic Design',
                'Branding Services',
                'Social Media Management',
                'Content Creation',
                'Copywriting',
                'Web Design',
                'Video Editing',
                'Animation Services',
            ],

            'Photography, Media & Production' => [
                'Studio Photography',
                'Event Photography',
                'Product Photography',
                'Drone Photography',
                'Graduation Photoshoot',
                'Wedding Videography',
                'Corporate Video',
                'Livestreaming',
                'Drone Coverage',
                'Music Video Production',
                'Camera Rental',
                'Lens Rental',
                'Lights & Audio Rental',
                'Studio Rental',
                'Photobooth',
                '360 Video Booth',
                'Selfie Booth',
            ],

            'Wedding & Events Services' => [
                'Wedding Planning',
                'Wedding Coordination',
                'Bridal Services',
                'Prenup Services',
                'Event Styling',
                'Floral Design',
                'Catering Services',
                'Wedding Rentals',
                'Birthday Planning',
                'Corporate Events',
                'Baptismal Setup',
                'Debut Planning',
                'Sound & Lights Rental',
                'Event Hosting',
                'Entertainment Services',
            ],

            'Food & Hospitality Services' => [
                'Catering',
                'Food Tray Services',
                'Meal Preparation',
                'Bakery Services',
                'Coffee Shop',
                'Milk Tea Shop',
                'Food Cart',
                'Hotel Services',
                'Hostel Services',
                'Resort Services',
                'Airbnb Management',
                'Travel & Tours',
            ],

            'Real Estate & Property Services' => [
                'Condo Selling',
                'House & Lot Selling',
                'Lot Selling',
                'Commercial Property Selling',
                'Foreclosed Property Assistance',
                'Apartment Rental',
                'Bedspace Rental',
                'Condo Rental',
                'Office Space Rental',
                'Coworking Space Rental',
                'Event Space Rental',
                'Studio Rental',
                'Warehouse Rental',
                'Property Management',
                'Real Estate Consultation',
                'Brokerage Services',
                'Property Documentation Assistance',
            ],

            'Rental & Leasing Services' => [
                'Construction Equipment Rental',
                'Tool Rental',
                'Generator Rental',
                'Gown Rental',
                'Suit Rental',
                'Sound System Rental',
                'Tent Rental',
                'Tables & Chairs Rental',
                'Car Rental',
                'Van Rental',
                'Motorcycle Rental',
            ],

            'Transportation & Logistics' => [
                'Delivery Services',
                'Courier Services',
                'Trucking Services',
                'Lipat Bahay Services',
                'Logistics Support',
            ],

            'Financial, Legal & Government' => [
                'Bills Payment',
                'Remittance Center',
                'Loan Assistance',
                'Insurance Services',
                'Investment Consultation',
                'Notarial Services',
                'Legal Consultation',
                'Visa Assistance',
                'Business Registration',
                'Permit Processing',
                'Tax Assistance',
            ],

            'Technology & IT Services' => [
                'Software Development',
                'Mobile App Development',
                'Internet Installation',
                'Network Setup',
                'Cybersecurity Services',
                'POS System Installation',
            ],

            'Community & Lifestyle Services' => [
                'Coworking Space',
                'Community Center',
                'Workshop Venue',
                'Training Facility',
                'Business Incubation Hub',
                'Freelancer Hub',
            ],

            'Retail & Commercial' => [
                'Convenience Store',
                'School Supplies Store',
                'Hardware Store',
                'Agricultural Supply Store',
                'Personal Care Retail',
                'Refill Station',
                'Pet Supply Store',
                'Vape Shop',
                'Gadget Store',
            ],

            'Agricultural & Environmental' => [
                'Gardening Services',
                'Landscaping',
                'Plant Nursery',
                'Urban Farming',
                'Hydroponics',
                'Composting Services',
                'Agricultural Consultation',
            ],

            'Specialized & Emerging Services' => [
                'Virtual Assistance',
                'Influencer Services',
                'E-commerce Support',
                'Franchise Consultancy',
                'Startup Consultancy',
                'Digital Marketing Agency',
                'NFT/Web3 Consultation',
                'AI Services',
                'Business Process Outsourcing (BPO)',
            ],
        ];

        foreach ($categories as $parentCategory => $subcategories) {
            foreach ($subcategories as $subcategory) {
                LifestyleCategory::updateOrCreate(
                    [
                        'name' => $subcategory,
                        'parent_category' => $parentCategory,
                    ],
                    []
                );
            }
        }
    }
}